### ISSUE TITLE
Eliminating OpenSSL Dependency for Enhanced Compatibility

### ISSUE THREAD

**Issue by JeyJeyGao** [Azure/notation-azure-kv#116]
In our testing, we discovered that the plugin is incompatible with OpenSSL versions earlier than v1.1.1h. This is due to our usage of X509Chain.Build(), which requires interfacing with the system's cryptography library. Older versions of OpenSSL do not support certificates generated by Azure Key Vault, leading to compatibility issues.

To resolve this, we've decided to eliminate the OpenSSL dependency. We will build the certificate chain by directly concatenating the leaf certificate and the certificate bundle, bypassing the need to validate the chain's integrity.

**Comment by shizhMSFT** [comment]
The removal of OpenSSL is for `v1.0.0`. We consider adding this functionality back post `v1.0.0` by detecting the supported OpenSSL versions.
