### ISSUE TITLE
authentication issues

### ISSUE THREAD

**Issue by gleb-boushev-effem** [Azure/notation-azure-kv#146]
trying to integrate into the GH actions pipeline I'm getting the following:

> Error: describe-key command failed: ERROR: Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot ERROR: Tenant shouldn't be specified for managed identity account

I'm seeing in the code its using DefaultAzureCredential and, somehow, fails at the cli auth. I do use `az login --identity --username xyz` for managed identity login and the agent itself is also capable of doing OIDC auth, yet somehow it still fails.

to clarify: az acr login works in the same job and i can succesfully push to the acr

Also looking at the code there appears to be no way to tweak the way you login (or pass existing token)

**Comment by yizha1** [comment]
@JeyJeyGao  Would you mind taking a look at this issue? 

@gleb-boushev-effem Are you using [notation GitHub actions ](https://github.com/marketplace/actions/notation-actions)?  @FeynmanZhou would you mind sharing the guideline on GitHub actions with AKV plugin experience?

**Comment by FeynmanZhou** [comment]
Hi @gleb-boushev-effem ,

There are two ways to connect GitHub Actions with your ACR and AKV: 

- [Use the Azure login action with a service principal secret](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#use-the-azure-login-action-with-a-service-principal-secret)
- [Use the Azure login action with OpenID Connect](https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#use-the-azure-login-action-with-openid-connect)

Could you try to follow this [guideline](https://github.com/notation-playground/notation-integration-with-ACR-and-AKV/blob/main/sign-action.md) to authenticate Azure services and use Notation GH Action?

**Comment by JeyJeyGao** [comment]
Hi @gleb-boushev-effem , could you provide more context about this issue? The ManagedIdentityCredential is designed to work on various Azure hosts that provide a managed identity. However, I want to reproduce the issue but am not sure how to use managed identity on GitHub action agents.

**Comment by JeyJeyGao** [comment]
Hi @gleb-boushev-effem, I found a potentially related issue that was fixed in [Azure.Identity](https://github.com/Azure/azure-sdk-for-net/pull/34078). Therefore, I bumped up the version of Azure.Identity and created a [private release](https://github.com/JeyJeyGao/notation-azure-kv/releases/tag/v1.1.1). Please give it a try. 

If it doesn't work, could you try a different authentication method provided by @FeynmanZhou , or provide detailed steps to reproduce the issue?

Thank you!

**Comment by yizha1** [comment]
@gleb-boushev-effem Would you mind providing any update on whether the private release from @JeyJeyGao solves your problem?
