### ISSUE TITLE
Empty error response when installing plugin on a mismatched Arch 

### ISSUE THREAD

**Issue by FeynmanZhou** [Azure/notation-azure-kv#148]
I installed Notation AKV plugin (Linux_arm64 version) on an Linux_amd64 machine. The error response is empty in `stderr` as follows. 

Should Notation AKV plugin returns that the Arch is not matched with the machine?

```
$ notation plugin install --file notation-azure-kv_1.0.1_linux_arm64.tar.gz -d
DEBU[2024-01-12T09:30:05Z] Extracting file notation-azure-kv...
DEBU[2024-01-12T09:30:06Z] Extracting file LICENSE...
DEBU[2024-01-12T09:30:06Z] Installing plugin from plugin path /tmp/notation-plugin1835003109
DEBU[2024-01-12T09:30:06Z] Plugin get-plugin-metadata request: {}
DEBU[2024-01-12T09:30:06Z] plugin get-plugin-metadata execution status: fork/exec /tmp/notation-plugin1835003109/notation-azure-kv: exec format error
DEBU[2024-01-12T09:30:06Z] Plugin get-plugin-metadata returned error:
Error: plugin installation failed: failed to get metadata of new plugin: ERROR: response is not in JSON format. error: fork/exec /tmp/notation-plugin1835003109/notation-azure-kv: exec format error, stderr:
```

**Comment by JeyJeyGao** [comment]
If the architecture does not match, the plugin will not be executable, and therefore, it returns nothing in STDERR and STDOUT.

> DEBU[2024-01-12T09:30:06Z] plugin get-plugin-metadata execution status: fork/exec /tmp/notation-plugin1835003109/notation-azure-kv: exec format error

This line indicates that the plugin is not executable due to a format error.

We should optimize the Notation-go error message to fix it.

**Comment by FeynmanZhou** [comment]
@Two-Hearts Shall we move this issue to notation-go and improve the error logs in the library instead for this case?

**Comment by Two-Hearts** [comment]
> @Two-Hearts Shall we move this issue to notation-go and improve the error logs in the library instead for this case?

@FeynmanZhou Sounds good to me.
