### ISSUE TITLE
error message improvement

### ISSUE THREAD

**Issue by JeyJeyGao** [Azure/notation-azure-kv#178]
> VALIDATION_ERROR: Invalid input. The valid input format is '{"contractVersion":"1.0","keyId":"https://<vaultname>.vault.azure.net/<keys|certificate>/<name>/<version>"}'
Error: Error: The process '/home/runner/work/_temp/b0e9f994-081d-44f1-88df-f056d94313f4/notation' failed with exit code 1

This error message is difficult to understand. We need to improve it by making it clearer, providing a descriptive message, and offering actionable suggestions.

**Comment by FeynmanZhou** [comment]
@JeyJeyGao See my suggested change in https://github.com/notaryproject/notation-go/issues/404#issuecomment-2128527193. Also linking to https://github.com/Azure/notation-azure-kv/issues/180 as an ultimate solution.

**Comment by JeyJeyGao** [comment]
Resolved in #181
