### ISSUE TITLE
Unable to verify the container image using "strict" level on the trust policy

### ISSUE THREAD

**Issue by madhav287** [Azure/notation-azure-kv#184]
level=error msg="authenticity validation failed. Failure reason: failed to validate the trusted certificate pub.pem in trust store codesigning-nonprod of type ca"

**Comment by yizha1** [comment]
@madhav287 Would you mind providing more information? Such as, Notation version, AKV plugin version, steps to reproduce the issue? Thanks.

**Comment by JeyJeyGao** [comment]
Hi @madhav287 ,  the trust store should store the root certificate of your signing certificate chain. Could you please ensure the `pub.pem` is a CA certificate?

**Comment by madhav287** [comment]
Hello all,

Can you please let me know your availability time to check on this issue?

Regards,
Sethumadhav

**Comment by JeyJeyGao** [comment]
Hello @madhav287, we can provide asynchronous support for GitHub issues. If you need 1:1 technical support, please create an Azure support ticket.

To investigate the issue further, we need more information. Could you provide the output for the following commands:
1. `notation cert list`
2. `notation cert show --type ca --store codesigning-nonprod pub.pem`

Thank you!

**Comment by madhav287** [comment]
++ @***@***.***

**Comment by madhav287** [comment]
Hello all,

our pipelines are running with notation version : v1.0.1 and AKV plugin version : v1.0.1,

We are passing root certificate on pub.pem while verifying the container image.

do let me know when and what time is suitable to connect on this issues.

Regards,
Sethumadhav


________________________________

**Comment by madhav287** [comment]
Hello all,

Any updates on this.

or do you want me to schedule a call to discuss on this.

Thanks,
Sethumadhav
________________________________

**Comment by yizha1** [comment]
@madhav287 It is recommended to create a support ticket for compliance and privacy purposes, as troubleshooting or logs may contain some information that is not supposed to be disclosed. See guidance https://learn.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request?

If you prefer to schedule a call for discussion, it is also OK, you can contact me via mail yizha1@microsoft.com, and we can discuss the schedule in the mail. Thanks.

**Comment by JeyJeyGao** [comment]
Closed this issue as it has been resolved in email threads.
