### ISSUE TITLE
Enable the currently logged in user, or MI of the node to access key vault

### ISSUE THREAD

**Issue by SteveLasker** [Azure/notation-azure-kv#20]
The current plug-in requires: `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET` and `AZURE_TENANT_ID`

The only way I can think of doing this is creating a service principal. Which means we either need to create a service principal each time, or save the SP in Key Vault. Which means I need access to key vault to get values out of key vault, to sign with key vault...

## Current Experience

Snippet from the current docs:  [Configure Azure Key Vault](https://github.com/Azure/notation-azure-kv/blob/main/docs/nv2-sign-verify-aks.md#configure-azure-key-vault)

- Use the currently logged in user

  ```bash
  # Use the current signed in user
  export AZURE_CLIENT_ID=$(az ad signed-in-user show --query objectId --output tsv)

  export AZURE_CLIENT_SECRET=$(az ad sp create-for-rbac --skip-assignment --name $SP_NAME --query "password" --output tsv)

  # Capture the Azure Tenant ID
  export AZURE_TENANT_ID=$(az account show --query "tenantId" -o tsv)
  ```

- Assign key and certificate permissions to the service principal object id

    ```bash
    az keyvault set-policy --name $AKV_NAME --key-permissions get sign --object-id $AZURE_CLIENT_ID

    az keyvault set-policy --name $AKV_NAME --certificate-permissions get --object-id $AZURE_CLIENT_ID
    ```

## Target Experience

I'm hoping we can use something from the `az ad signed-in-user show` command:

```bash
export AZURE_CLIENT_ID=$(az ad signed-in-user show --query objectId --output tsv)

# Capture the Azure Tenant ID
export AZURE_TENANT_ID=$(az account show --query "tenantId" -o tsv)
```

But, what would we set the `AZURE_CLIENT_SECRET` to:
```bash
export AZURE_CLIENT_SECRET=$(az ad sp create-for-rbac --skip-assignment --name $SP_NAME --query "password" --output tsv)
```

How can the `notation-azure-kv` understand how to use the currently logged in user for developer interactive models, or the managed identity of the node when run within a build environment that is using an Azure VM. The plug-in is only required for signing, so this wouldn't be needed for gatekeeper validations.

**Comment by qmuntal** [comment]
#18 simplifies and generalize the authorization workflow in the following ways:

- For development environments, it is no longer necessary to configure credentials. `notation-azure-kv` will authorize requests using the `az` logged-in user, which can be done by running `az login` in any terminal, it does not have to be the same terminal used for running the plugin.
- For production environments, one still need to use service principals, the recommended authorization path. The exception is when the host supports Azure Managed Identities, which is the case for Azure VM. In this case, you can try setting up the managed identities environment, and the plugin will try to use it. Haven't done it myself, so I can only point you to the docs: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview?msclkid=690a3f24cf6511ec81d8c07e5159e642

**Comment by qmuntal** [comment]
@SteveLasker we can close this issue. As of #18 `notation-azure-kv` understands users logged-in using `az login` and Managed Identities.
