### ISSUE TITLE
Simplify configuration for Key Vault Key Id

### ISSUE THREAD

**Issue by SteveLasker** [Azure/notation-azure-kv#21]
The current experiences requires the user to provide `--id` to `notation cert add` which requires a more complex az cli command to configure.
The goal here would be to simply the configuration by simply providing the Key Vault Certificate Name. The Notation Azure Key Vault plugin would resolve the fully qualified path

```bash
KEY_ID=$(az keyvault certificate show \
                        --vault-name wabbitnetworks \
                        --name wabbit-networks-io \
                        --query "kid" -o tsv)

notation key add \
    --name wabbit-networks-io \
    --plugin azure-kv \
    --id $KEY_ID \
    --kms
```

To simplify this, the notation-azure-keyvault plugin should have it's own configuration file, or a simpler means to pass values through the notation cli
`notation plugin configure --name azure-kv --config keyvault=wabbitnetworks --config certificate-name=wabbit-networks-io`

Other options might be the notation.config file.
Things to consider
How would a production system configure an ephemeral build machine? The machine would pull some configuration information from a configuration service, including the trust policies. Is it reasonable to add these remote signing service configurations to the same config?

**Comment by qmuntal** [comment]
The plugin spec already accounts for this use-case by defining key-specific [plugin configurations](https://github.com/notaryproject/notaryproject/blob/main/specs/plugin-extensibility.md#plugin-configuration), and notation@main already supports it.

We just have to do some small changes in our side to define how to pass the vault name and the key name in the plugins request. A working prototype is available at #22 .
