### ISSUE TITLE
 Admission webhook "validation.gatekeeper.sh" denied the request: [ratify-constraint] Subject failed

### ISSUE THREAD

**Issue by giannicaru** [Azure/notation-azure-kv#31]
Hi @dtzar @akashdubey-ms 
i have this error message back once that i try to push a signed image on aks : 

"Error from server (Forbidden): admission webhook "validation.gatekeeper.sh" denied the request: [ratify-constraint] Subject failed verification: condemogianni.azurecr.io/net-monitor:v1"

do you have any idea about how solve it ? 
thanks 
GIanni

**Comment by etrexel** [comment]
Hi Gianni,

This looks like an image verification failure coming from what I assume is an external data request to Ratify. This can happen for a number of reasons.

Did you install Ratify via the chart, and if so can you share the version you are using? It would also help to know what Constraint and ConstraintTemplate you are using. Can you also provide the YAML you are applying to deploy the pod?

You can get some more information on what happened during the verification by checking the Ratify logs. The most likely issues are missing artifacts in the registry, missing CAs in the Ratify pod, registry authentication issues, or a bug 😄.

Just to confirm, you are only using the notation-azure-kv plugin for signing the container image correct? Ratify does not leverage this plugin to get certificates from AKV as this plugin only applies to the notation CLI.

**Comment by giannicaru** [comment]
Hi
[logratifypod.txt](https://github.com/Azure/notation-azure-kv/files/9468396/logratifypod.txt)
![ratify version](https://user-images.githubusercontent.com/105774805/187875245-0df3c1de-9c9a-4b4d-bc3a-d98506483316.png)
![helm version](https://user-images.githubusercontent.com/105774805/187875255-163e9294-412e-47d3-bd01-bc7d6b3501b6.png)
,
thank you very much for the quick reply; I am attaching screenshots of what was requested and an extract of the ratify logs; as for the notation-azure-kv plugin for signing the container image, yes that's what I'm using


thanks 
Gianni

**Comment by etrexel** [comment]
Based on the initial log messages from the request it looks like the image `myregistry.azurecr.io/net-monitor:v1` is what is being verified. We shouldn't have any placeholders in Ratify code that have that value which would make me think this is either coming from the ConstraintTemplate, Constraint, or the YAML you are applying. 

Are you making any adjustments to the ConstraintTemplate or Constraint? If not can you provide the YAML you are applying that is causing this failure? Is this the image that is actually referenced by that YAML?

**Comment by giannicaru** [comment]
hi @etrexel  , no i'm using the default one :

kubectl apply -f https://deislabs.github.io/ratify/library/default/template.yaml
kubectl apply -f https://deislabs.github.io/ratify/library/default/samples/constraint.yaml

nothing different

**Comment by dtzar** [comment]
@giannicaru - I also noticed the log reference of "myregistry" with the `net-monitor` image. This shows up in the logs even when you run this command with the image I assume does exist in ACR?

`kubectl run net-monitor --image=condemogianni.azurecr.io/net-monitor:v1`

**Comment by giannicaru** [comment]
hi , i tried to update the notation key vault plugin version to v0.3.1 and installed again all configuration but i have the same problem :
```
kubectl run net-monitor --image=containernotaryv2aks.azurecr.io/net-monitor:v1
Error from server (Forbidden): admission webhook "validation.gatekeeper.sh" denied the request: [ratify-constraint] Subject failed verification: containernotaryv2aks.azurecr.io/net-monitor:v1
```

and on ratify pod i have this log : 
```
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
"isSuccess": false,
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
"verifierReports": [
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
{
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
"subject": "containernotaryv2aks.azurecr.io/net-monitor:v1",
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
"isSuccess": false,
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
"message": "verification failed: resolving descriptor for the subject failed with error could not resolve descriptor for a subject from any stores"
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
}
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
]
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
}
7/9/2022, 10:07:19
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
time="2022-09-07T08:07:19Z" level=warning msg="failed to resolve the subject descriptor from store oras with error HEAD \"https://containernotaryv2aks.azurecr.io/v2/net-monitor/manifests/v1\": GET \"https://containernotaryv2aks.azurecr.io/oauth2/token?scope=repository%3Anet-monitor%3Apull&service=containernotaryv2aks.azurecr.io\": unexpected status code 401: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.\n"
7/9/2022, 10:07:53
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
time="2022-09-07T08:07:53Z" level=info msg="received request POST /ratify/gatekeeper/v1/verify "
7/9/2022, 10:07:53
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
time="2022-09-07T08:07:53Z" level=info msg="start request POST /ratify/gatekeeper/v1/verify"
7/9/2022, 10:07:53
ratify-68f59954c-kf89d
cf6ec7da36584fa5be5f9dd0fb5722d8e8fd90a4507a8468c7fb0158a8eae7d7
time="2022-09-07T08:07:53Z" level=info msg="subject for request POST /ratify/gatekeeper/v1/verify is ghcr.io/deislabs/ratify:v1.1.0-alpha.1"
```

**Comment by etrexel** [comment]
The error logs from the ratify pod include `unexpected status code 401: unauthorized: authentication required`. Is the registry you are using public? If not have you configured ratify with the necessary credentials to access the registry?

**Comment by giannicaru** [comment]
i'm using a public registry yes

**Comment by dtzar** [comment]
@giannicaru - there have been a number of new releases to ratify, notation, and notation-azure-kv plugin since this issue and all of our e2e and manual tests are passing.  Please let us know if you are still experiencing any issues going through the setup from start again.

**Comment by dtzar** [comment]
@giannicaru - there have been a number of new releases to ratify, notation, and notation-azure-kv plugin since this issue and all of our e2e and manual tests are passing.  Please let us know if you are still experiencing any issues going through the setup from start again.

**Comment by giannicaru** [comment]
thanks a lot @dtzar so I'll try to play with the newest one as soon as possible ;)
