### ISSUE TITLE
Supporting certificate chain in plugin

### ISSUE THREAD

**Issue by chloeyin** [Azure/notation-azure-kv#36]
Currently, only self-signed certificate is supported by the plugin.
By trying sdk and azure-cli, `az keyvault certificate download` can only download the leaf certificate. (https://learn.microsoft.com/en-us/answers/questions/441132/retrieving-certificate-with-complete-chain-from-az.html)
When using `az keyvault secret download`, the whole chain can be downloaded, but probably with a private key inside. 
I've checked default policy, the `"exportable": true` indicates that by default, private key is exportable.
```
az keyvault certificate get-default-policy
{
  "issuerParameters": {
    "certificateTransparency": null,
    "name": "Self"
  },
  "keyProperties": {
    "curve": null,
    "exportable": true,
    "keySize": 2048,
    "keyType": "RSA",
    "reuseKey": true
  },
  "lifetimeActions": [
    {
      "action": {
        "actionType": "AutoRenew"
      },
      "trigger": {
        "daysBeforeExpiry": 90
      }
    }
  ],
  "secretProperties": {
    "contentType": "application/x-pkcs12"
  },
  "x509CertificateProperties": {
    "keyUsage": [
      "cRLSign",
      "dataEncipherment",
      "digitalSignature",
      "keyEncipherment",
      "keyAgreement",
      "keyCertSign"
    ],
    "subject": "CN=CLIGetDefaultPolicy",
    "validityInMonths": 12
  }
}
``` 
I don't find a way to get the whole certificate chain without using keyvault's secret API. If the plugin is going to support certificate chain and using `secret download`, should we enforce that user should not export their private key? I don't know why keyvault will export the private key be default. Actually, current [doc](https://learn.microsoft.com/en-us/answers/questions/441132/retrieving-certificate-with-complete-chain-from-az.html) will export the private key, which will fail the certificate parsing step and may leak user's private key.

**Comment by shizhMSFT** [comment]
Closing this issue since it is outdated.
