### ISSUE TITLE
notation authentication problem

### ISSUE THREAD

**Issue by dtzar** [Azure/notation-azure-kv#40]
I am logged in with az on windows 11 with powershell using latest 0.11.0-alpha.4 version of notation client and latest version of plugin 0.4.0-alpha.4 with an Azure key vault key added into notation.  When I try to sign with the AKV key, it continues to give this error:

```
notation sign --envelope-type cose localhost:5000/net-monitor:demo --key acme-rockets-io --plain-http
Error: describe-key command failed: azure-kv: VALIDATION_ERROR: authorized from Azure CLI 2.0 failed, please ensure you have logged in using the 'az' command line tool, origin error: Invoking Azure CLI failed with the following error: 'az' is not recognized as an internal or external command, operable program or batch file.

2022/10/26 00:35:18 describe-key command failed: azure-kv: VALIDATION_ERROR: authorized from Azure CLI 2.0 failed, please ensure you have logged in using the 'az' command line tool, origin error: Invoking Azure CLI failed with the following error: 'az' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by yizha1** [comment]
@dtzar I just saw this issue. Do you remember this problem was solved?

**Comment by dtzar** [comment]
I don't think I ever got a resolution.  That said - I'm fine to close it out if we know this scenario has been tested with the latest bits.

**Comment by shizhMSFT** [comment]
Closing this issue as it is outdated.

@dtzar Please open a new issue if you still have this problem with the latest plugin.
