### ISSUE TITLE
The version info of plug is too long

### ISSUE THREAD

**Issue by yizha1** [Azure/notation-azure-kv#46]
The version info of the plugin is too long, which mess the output of `notation plugin ls`

What is the reason to show the commit id in the version info? If we do need the commit id, how about displaying a short version of commit id?

```
$ notation plugin ls
NAME       DESCRIPTION                                   VERSION
    CAPABILITIES                ERROR
azure-kv   Sign artifacts with keys in Azure Key Vault   0.4.0-beta.1+7aa39fbfe7014000f015eea3e3b2604ab6dc0deb   [SIGNATURE_GENERATOR.RAW]   <nil>
```

**Comment by FeynmanZhou** [comment]
Completed by https://github.com/Azure/notation-azure-kv/pull/50 so close it
