### ISSUE TITLE
Default to `Certificate / Get` for Cert Chain

### ISSUE THREAD

**Issue by shizhMSFT** [Azure/notation-azure-kv#63]
Based on the description of #58 and the following code 
https://github.com/Azure/notation-azure-kv/blob/f186c0fa79d73c7d21f464cdb1af7e83d3566b03/internal/cloud/keyvault.go#L170-L188

we require `Secret/Get` permission for the certificate chain even if the ca certs are provided by the plugin config `ca_certs`.

To apply the principle of [least privileged access](https://learn.microsoft.com/azure/active-directory/develop/secure-least-privileged-access), we should default to `Certificate / Get` (Get Certificate) and only attempt `Secret/Get` (Get Certificate and Secret) when the plugin config `as_secret` is toggled to `true` or `1`.

**Comment by yizha1** [comment]
How about the config name `get_secret`?

**Comment by shizhMSFT** [comment]
`cert-chain=true` can be implied by non-empty `ca_certs`.
